[project]
name = "loopify"
version = "1.0.0"
description = "Automate Your API Calls"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "streamlit>=1.51.0",
    "uncurl>=0.0.11",
]
